apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: express-app
  name: express-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
        - image: gcr.io/neon-framing-303105/github.com/rohitabraham02/nodejs
          imagePullPolicy: IfNotPresent
          name: nodejs-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: express-app
  name: express-app-hpa-2s95
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: express-app
---
apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  generateName: express-app-
  labels:
    app: express-app
  name: express-app-2g9z6
  namespace: default
spec:
  clusterIP: 10.8.7.87
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 31233
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: express-app
  sessionAffinity: None
  type: LoadBalancer
